# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-04 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemas',
            name='id',
        ),
        migrations.AlterField(
            model_name='problemas',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
