# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=20)),
                ('Carrera', models.CharField(choices=[('Matem\xe1tico', 'Matem\xe1tico'), ('F\xedsico', 'F\xedsico')], max_length=20)),
                ('Nombres', models.CharField(max_length=35)),
                ('Apellidos', models.CharField(max_length=35)),
                ('Correo', models.CharField(max_length=60, unique=True)),
                ('CUI', models.CharField(max_length=20)),
            ],
        ),
    ]
