# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 04:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textos',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Tex_id', models.AutoField(primary_key=True, serialize=False)),
                ('Texto', models.FileField(upload_to='archivos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'pm2'])])),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=20)),
                ('Carrera', models.CharField(choices=[('Matem\xe1tico', 'Matem\xe1tico'), ('F\xedsico', 'F\xedsico')], max_length=20)),
                ('Nombres', models.CharField(max_length=35)),
                ('Apellidos', models.CharField(max_length=35)),
                ('Correo', models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Correo no v\xe1lido', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')])),
                ('CUI', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Debes ingresar un n\xfamero de 13 d\xedgitos', regex='^\\+?1?\\d{13}$')])),
                ('EstaActivo', models.CharField(default='No', max_length=20)),
            ],
        ),
    ]
