# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 23:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='CUI',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Debes ingresar un n\xfamero de 13 d\xedgitos', regex='^\\+?1?\\d{13}$')]),
        ),
    ]
