# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 23:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20180307_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Correo',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Correo no v\xe1lido', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')]),
        ),
    ]
